# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:46
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k18', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='event',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'TME', b'MODELEXPO'), (b'IIP', b'Brainwave'), (b'QUIZ', b'Examen-The Quiz'), (b'APP', b'MAD'), (b'RNG', b'Rangmanch'), (b'OSD', b'Creations')], max_length=100),
        ),
    ]
